### ISSUE TITLE
在项目中设置无效 iOS11.2系统

### ISSUE THREAD

**Issue by jueying-xiangfeng** [Mervin1024/NavigationBackItemDemo#1]
在项目中设置无效 iOS11.2系统，但是用你的demo没问题，我的rootVC是tabbarcontroller，初始化时会先调用iOS11CustomPushNavigationItem这个方法，你的demo是不走的，然后我把self.topItem.backBarButtonItem的判空条件去掉，设置也无效，能帮忙分析一下吗?

**Comment by Mervin1024** [comment]
你好。

我在实际使用的项目中，rootVC也是UITabbarViewController，这个是没有影响的。

你可以尝试确认下，被 push 出来的新的 UIViewController 是没有过自定义过 navigationItem.leftBarButtonItem 或者 navigationItem.leftBarButtonItems 属性的。

在 iOS 11 及以上的系统中，- (void)iOS11CustomPushNavigationItem:(UINavigationItem *)item animated:(BOOL)animated 会在push操作时触发，所做的是为 UIViewController 的 navigationItem.backBarButtonItem 赋值。而在.leftBarButtonItem 或者 .leftBarButtonItems 属性生效时，.backBarButtonItem 是不会生效的。

你可以通过断点调试等方式查看被 push 出来的 VC 的 navigationItem 中的各个属性，确认只存在 backBarButtonItem 而 leftBarButtonItem 或者 leftBarButtonItems 为 nil 的话，仍无效，请再联系我 。

**Comment by Mervin1024** [comment]
抱歉，最后一段描述有误。

A push 到 B。

请检查 push 完成后的 B 的 navigationItem.leftBarButtonItem 和 navigationItem.leftBarButtonItems 属性，以及 A 的 navigationItem.backBarButtonItem 属性， 是否同时有值。

**Comment by jueying-xiangfeng** [comment]
不好意思,当时通过别的方式实现了就没有再看，刚用最新的版本试了一下，我在AppDelegate里面设置完[UINavigationBar appearance].mer_globalBackBarButtonTitle后没有立刻调用mer_globalBackBarButtonTitle的set方法。
我的结构是一个tabbarControler，每个tab对应一个NavVC，我的vc是手动写的，初步发现在设置完rootVC后会调用pushViewController:animated: 方法，进而调用类别里面的mer_customPushNavigationItem:animated:方法，由于此时还没有调用mer_globalBackBarButtonTitle的set方法，在生成mer_globalBackBarButtonItem时title为空，会用默认的"返回"文案，以后在调用时mer_globalBackBarButtonItem已经生成，文字会用默认的文案。
这是我在appDelegate里面的调用 :
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [UINavigationBar appearance].mer_globalBackBarButtonTitle = @"123";
    [self setRootViewController];
    [self registerRemoteNotification];
    return YES;
}`
至于为什么没有先调用mer_globalBackBarButtonTitle的set方法还不太清楚，还有代码和storeboard对调用顺序的影响我晚上再试试，表达比较乱，博主大神看一下能分析出是哪里的问题不。
上次看完博主的黑科技受益良多, 多谢分享 (^_^)! @Mervin1024
